#ifndef ACTUATOR_STATE_H
#define ACTUATOR_STATE_H

#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_ON           0x00
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_OFF          0x01
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_17      0x02
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_18      0x03
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_19      0x04
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_20      0x05
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_21      0x06
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_22      0x07
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_23      0x08
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_24      0x09
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_25      0x0A
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_26      0x0B
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_27      0x0C
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_28      0x0D
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_29      0x0E
#define IPAC_UNIVERSAL_IR_CONTROLLER_STATE_TEMP_30      0x0F

#endif /* ACTUATOR_STATE_H */