#ifndef MODEL_H
#define MODEL_H

// model definitions
#define CID_ESP                 0x02E5

#define DEVICE_INFO_MODEL_ID_SERVER      0x1400
#define DEVICE_INFO_MODEL_ID_CLIENT      0x1401
#define DEVICE_INFO_MODEL_OPCODE_GET     ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
#define DEVICE_INFO_MODEL_OPCODE_STATUS  ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)

#define SENSOR_MODEL_ID_SERVER  0x1414
#define SENSOR_MODEL_ID_CLIENT  0x1415
#define SENSOR_MODEL_OPCODE_GET     ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
#define SENSOR_MODEL_OPCODE_SET     ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
#define SENSOR_MODEL_OPCODE_STATUS  ESP_BLE_MESH_MODEL_OP_3(0x02, CID_ESP)

#define AC_CONTROL_MODEL_SERVER     0x1416
#define AC_CONTROL_MODEL_CLIENT     0x1417
#define AC_CONTROL_STATE_OPCODE_GET        ESP_BLE_MESH_MODEL_OP_3(0x00, CID_ESP)
#define AC_CONTROL_STATE_OPCODE_SET        ESP_BLE_MESH_MODEL_OP_3(0x01, CID_ESP)
#define AC_CONTROL_STATE_OPCODE_STATUS     ESP_BLE_MESH_MODEL_OP_3(0x02, CID_ESP)

#endif  /* MODEL_H */